version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:18.16 
    steps:
      - checkout

      - run:
          name: Install npm packages
          command: npm ci || npm install

      - run:
          name: Run Jest tests
          command: npm test

workflows:
  build-and-test:
    jobs:
      - test
